language: csharp
sudo: required
dist: xenial
mono: none
dotnet: 2.2.103
install:
- dotnet restore
script:
- dotnet build
- dotnet test MeanCards.Tests.Integration/MeanCards.Tests.Integration.csproj
- dotnet test MeanCards.Tests.Unit/MeanCards.Tests.Unit.csproj